### ISSUE TITLE
specific cryptocurrency

### ISSUE THREAD

**Issue by carasino2021** [brianleect/binance-pump-alerts#1]
How could it be modified for a specific cryptocurrency?
example only see ADAUSDT every 5 seconds

thanks

**Comment by brianleect** [comment]
I have updated the program to consider watchlist. You should be able to achieve what you want by adding 'ADAUSDT' to the watchlist under params.py.

You can adjust the '5s' parameter to the value you need as well eg. 0.03 which will send a message when >= 3% difference for ADAUSDT price is observed.

**Comment by brianleect** [comment]
Closing as issue has been resolved.
