### ISSUE TITLE
Problem with timeframes larger than 5m

### ISSUE THREAD

**Issue by Majenunez** [brianleect/binance-pump-alerts#11]
Hi, I want to receive alerts for longer periods such as 5m, 15m, 30m, 1h, etc. And I would like percentage changes of 5%, 10%, etc. So my configuration file has been as follows:

_intervals = ['5m', '15m', '30m', '1h']
outlier_param = {'5m': 0.05, '5m': 0.1, '15m': 0.05, '15m': 0.1, '30m': 0.05, '30m': 0.1,}_

But after obtaining the prices:

_"Added symbol: ADAUSDT
Added symbol: SNXUSDT
Added symbol: DOGEUSDT
Added symbol: BZRXUSDT
Added symbol: SKLUSDT"_

The Script gets stuck in the following bubcle and does not continue:

_"Time taken to extract and append: 0.6562504768371582
Extracting after 1s
Time taken to extract and append: 0.7968761920928955
Extracting after 1s
Time taken to extract and append: 0.7186744213104248
Extracting after 1s
Time taken to extract and append: 0.8281247615814209
Extracting after 1s
Time taken to extract and append: 0.9391098022460938
Extracting after 1s
Time taken to extract and append: 0.9218747615814209
Extracting after 1s
Time taken to extract and append: 0.9999191761016846
Extracting after 1s
Time taken to extract and append: 0.5155398845672607"_

And finally I have to stop it.

It should be noted that with the following configuration I can receive alerts but they are repeated a lot and generate Spam:

_"intervals = ['1s', '5s', '15s', '30s', '1m']
outlier_param = {'1s': 0.01, '5s': 0.03, '15s': 0.05, '30s': 0.06, '1m': 0.07, '5m': 0.10}"_

I'm not really sure if I'm setting something wrong or there could be an error with the large timeframes.

**Comment by Majenunez** [comment]
To avoid spam in notifications, I think that only one alert should be generated per Pair (without repeating). And continue with the alert for the next Pair. 

That is, once it alerts, it should be muted for a time interval that can be defined by the user (muting can be optional and it is up to each one). And then continue with the next pair and so on. 

This way the notifications would be better organized and better utilized.

**Comment by brianleect** [comment]
> Hi, I want to receive alerts for longer periods such as 5m, 15m, 30m, 1h, etc. And I would like percentage changes of 5%, 10%, etc. So my configuration file has been as follows:
> 
> _intervals = ['5m', '15m', '30m', '1h'] outlier_param = {'5m': 0.05, '5m': 0.1, '15m': 0.05, '15m': 0.1, '30m': 0.05, '30m': 0.1,}_
> 
> But after obtaining the prices:
> 
> _"Added symbol: ADAUSDT Added symbol: SNXUSDT Added symbol: DOGEUSDT Added symbol: BZRXUSDT Added symbol: SKLUSDT"_
> 
> The Script gets stuck in the following bubcle and does not continue:
> 
> _"Time taken to extract and append: 0.6562504768371582 Extracting after 1s Time taken to extract and append: 0.7968761920928955 Extracting after 1s Time taken to extract and append: 0.7186744213104248 Extracting after 1s Time taken to extract and append: 0.8281247615814209 Extracting after 1s Time taken to extract and append: 0.9391098022460938 Extracting after 1s Time taken to extract and append: 0.9218747615814209 Extracting after 1s Time taken to extract and append: 0.9999191761016846 Extracting after 1s Time taken to extract and append: 0.5155398845672607"_
> 
> And finally I have to stop it.
> 
> It should be noted that with the following configuration I can receive alerts but they are repeated a lot and generate Spam:
> 
> _"intervals = ['1s', '5s', '15s', '30s', '1m'] outlier_param = {'1s': 0.01, '5s': 0.03, '15s': 0.05, '30s': 0.06, '1m': 0.07, '5m': 0.10}"_
> 
> I'm not really sure if I'm setting something wrong or there could be an error with the large timeframes.



Thank you for your input @Majenunez , regarding the script repeatedly printing extraction and time taken, it is an expected output and there is no issue regarding it. I had it printed for debugging purposes initially. I have added a parameter 'PRINT_DEBUG' which you can set to False to disable the messages that is sent to console. Before turning it off I do recommend ensuring that extraction process is < 1s else while it would still work, it might be a little wonky.

**Comment by brianleect** [comment]
> To avoid spam in notifications, I think that only one alert should be generated per Pair (without repeating). And continue with the alert for the next Pair.
> 
> That is, once it alerts, it should be muted for a time interval that can be defined by the user (muting can be optional and it is up to each one). And then continue with the next pair and so on.
> 
> This way the notifications would be better organized and better utilized.

The issue of spam has been noted previously as well but largely ignored due to the focus on shorter time frames between '1s' to '1m'. Your point on skipping the pair entirely once an alert is triggered on an earlier interval has been integrated into the code. 

I also added a parameter I believe you would find useful defined as 'MIN_ALERT_INTERVAL' which you can set the minimum time before another alert is triggered for the specific pair. For your case I believe setting it to '5m' would fit your needs.

I'm not entirely sure if it would work entirely as intended as I have yet to fully test it. I'm currently running the updated script on the demo telegram channel to see if any errors pops out in the meantime. Do try running it and let me know if you face any other issues.

Cheers!

**Comment by Majenunez** [comment]
> > To avoid spam in notifications, I think that only one alert should be generated per Pair (without repeating). And continue with the alert for the next Pair.
> > That is, once it alerts, it should be muted for a time interval that can be defined by the user (muting can be optional and it is up to each one). And then continue with the next pair and so on.
> > This way the notifications would be better organized and better utilized.
> 
> The issue of spam has been noted previously as well but largely ignored due to the focus on shorter time frames between '1s' to '1m'. Your point on skipping the pair entirely once an alert is triggered on an earlier interval has been integrated into the code.
> 
> I also added a parameter I believe you would find useful defined as 'MIN_ALERT_INTERVAL' which you can set the minimum time before another alert is triggered for the specific pair. For your case I believe setting it to '5m' would fit your needs.
> 
> I'm not entirely sure if it would work entirely as intended as I have yet to fully test it. I'm currently running the updated script on the demo telegram channel to see if any errors pops out in the meantime. Do try running it and let me know if you face any other issues.
> 
> Cheers!

Ok thank you very much. I will try.

I have the doubt how I should set the parameters correctly. Could you clarify me?

For example suppose I want to receive an alert for the following scenario:

- 5% and 10% price change for 4 minutes and 15 minutes temporalities:

To my understanding the configuration would be like this:

intervals = ['4m', '15m'] 
outlier_param = {'4m': 0.05, '4m': 0.1, '15m': 0.05, '15m': 0.1} 

Would it be ok this way? 

Because you could also work each interval separately, but you would have to run two separate scripts:

intervals = ['4m'] 
outlier_param = {'4m': 0.05, '4m': 0.1} 

intervals = ['15m'] 
outlier_param = {'15m': 0.05, '15m': 0.1} 

What would be the most optimal way? 

Thank you very much for clarifying my doubts.
