### ISSUE TITLE
[Possible Feature] Periodic Price Alert

### ISSUE THREAD

**Issue by brianleect** [brianleect/binance-pump-alerts#16]
Could possibly set customizable parameters e.g. send price updates every X seconds.

Recommended to separate from the pump alerts telegram bot to prevent clash when sending multiple messages. 

Simple implementation but not on priority unless feature is requested for.

**Comment by Juanjacinto123** [comment]
> Could possibly set customizable parameters e.g. send price updates every X seconds.
> 
> Recommended to separate from the pump alerts telegram bot to prevent clash when sending multiple messages.
> 
> Simple implementation but not on priority unless feature is requested for.

It would be very interesting to add Alerts of the Top 5 or Top 10 coins that have had the highest Dumps and Pumps during X time interval. This would give us an idea of which coins during that X time interval have been dominating the market.

For example:

Top 5. Last 60 minutes (ordered by highest Pump) 

1. Dash, +7%, -3.5%, -3.5%
2. Ltc, +5%, -3.3%
3. Rvn, +3%, -2.7%
4. Gtc, +2%, -2.1%
5. Axs, +1%, -1.3%

Translated with www.DeepL.com/Translator (free version)

**Comment by brianleect** [comment]
> > Could possibly set customizable parameters e.g. send price updates every X seconds.
> > Recommended to separate from the pump alerts telegram bot to prevent clash when sending multiple messages.
> > Simple implementation but not on priority unless feature is requested for.
> 
> It would be very interesting to add Alerts of the Top 5 or Top 10 coins that have had the highest Dumps and Pumps during X time interval. This would give us an idea of which coins during that X time interval have been dominating the market.
> 
> For example:
> 
> Top 5. Last 60 minutes (ordered by highest Pump)
> 
> 1. Dash, +7%, -2.5%
> 2. Ltc, +5%, -3.3%
> 3. Rvn, +3%, -4.7%
> 4. Gtc, +2%, -2.1%
> 5. Axs, +1%, -1.3%

Thanks for the input I'll take a look at it later today. The current program structure should result in implementation quite simple. Definitely an interesting feature.

**Comment by Juanjacinto123** [comment]
> @Juanjacinto123 , you can checkout the latest version. I tested it on a '1m' interval and it seems to work.
> 
> ![image](https://user-images.githubusercontent.com/63389110/126532000-10c8b4e6-ff93-4e18-9534-ca435db46493.png)
> 

This new feature is great!

> In the latest version, I re-arranged the code to prevent the main file from being too clogged up. Parameters have been re-organized as well.
> 
> You should be able to customize the number of coins you wish to view and the interval this alert is sent.
> 

I have a question. If the highest temporality for Dumps and Pumps alerts is 30m and the Reset interval is 3h, the new feature would be able to alert the Tops at temporalities higher than 30m and lower than 3h? More precisely, what would be the maximum alert interval for this new feature?

> ![image](https://user-images.githubusercontent.com/63389110/126532184-48e3407e-7ab6-443d-ba4a-82e2785a37f5.png)
> 
> Currently it sends the message to the same group as pump/dump alerts. Let me know if you would prefer it to send to be able to send to another group instead.

I think it would be more useful to have both options; send them to the same group or to any other.

**Comment by brianleect** [comment]
> I have a question. If the highest temporality for Dumps and Pumps alerts is 30m and the Reset interval is 3h, the new feature would be able to alert the Tops at temporalities higher than 30m and lower than 3h? More precisely, what would be the maximum alert interval for this new feature?

@Juanjacinto123 ,
Regarding the max alert interval, it is indeed limited by the RESET_INTERVAL parameter. The '3h' default RESET_INTERVAL is a conservative value I choose. While running on the ec2 server without any RESET_INTERVAL previously, MEM_ERROR which crashed the program actually occurred >24 hours of continuous runtime. Adjusting to '12h' or '16h' RESET_INTERVAL should not be an issue in my opinion but it the absolute max duration that can be handled will likely differ for machine to machine.

The maximum ALERT_INTERVAL would in theory be any duration < RESET_INTERVAL. If I modify the code slightly to include some buffer to RESET_INTERVAL, we could set ALERT_INTERVAL to RESET_INTERVAL so '3h' could work.

For your use case, you could consider setting RESET_INTERVAL to a larger value '12h' or perhaps even '24h' and see if your VPS is able to handle it. With a larger buffer of RESET_INTERVAL, we would be able to get more insightful top pump/dumps on larger intervals.

There might also be a possible bug where we attempt to send an alert after a recent reset has been triggered. I have yet to test this case. In theory it would end up sending a message with all change being 0% due to the lack of data points.

> I think it would be more useful to have both options; send them to the same group or to any other.

Ok I'll add an option for this. Thanks for the input Juan.

**Comment by Juanjacinto123** [comment]
I am getting this error:

extrracting after 60 s
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 65, in <module>
  File "<string>", line 49, in checkTimeSinceReset
  File "/storage/emulated/0/Documents/binance-pump-alerts-master/functions.py", line 18, in durationToSeconds
    unit = str_dur[-1]
TypeError: 'int' object is not subscriptable

**Comment by brianleect** [comment]
> I am getting this error:
> 
> extrracting after 60 s
> Traceback (most recent call last):
> File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in
> start(fakepyfile,mainpyfile)
> File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
> exec(open(mainpyfile).read(), **main**.**dict**)
> File "", line 65, in
> File "", line 49, in checkTimeSinceReset
> File "/storage/emulated/0/Documents/binance-pump-alerts-master/functions.py", line 18, in durationToSeconds
> unit = str_dur[-1]
> TypeError: 'int' object is not subscriptable

My bad, added a line that broke in on accident. I have fixed the bug. Added an option to specify different group to send message for the top pump and/or dumps.

You can try the latest updated version @Juanjacinto123

**Comment by Juanjacinto123** [comment]
> > I am getting this error:
> > extrracting after 60 s
> > Traceback (most recent call last):
> > File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in
> > start(fakepyfile,mainpyfile)
> > File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
> > exec(open(mainpyfile).read(), **main**.**dict**)
> > File "", line 65, in
> > File "", line 49, in checkTimeSinceReset
> > File "/storage/emulated/0/Documents/binance-pump-alerts-master/functions.py", line 18, in durationToSeconds
> > unit = str_dur[-1]
> > TypeError: 'int' object is not subscriptable
> 
> My bad, added a line that broke it on accident. I have fixed the bug. Added an option to specify different group to send message for the top pump and/or dumps.
> 

It is working well right now. 

> You can try the latest updated version @Juanjacinto123

**Comment by Juanjacinto123** [comment]
Several values could be configured for the ALERT_INTERVAL.

For example: 

For the 12-hour reset interval, send the Tops alert for the last hour, the last 3h and the last 6h. 

In this way we can have an idea of what would be the market sentiment at various timeframes.

**Comment by brianleect** [comment]
> Several values could also be configured for the ALERT_INTERVAL.
> 
> For example:
> 
> For the 12-hour reset interval, send the Tops alert for the last hour, the last 3h and the last 6h.
> 
> In this way we can have an idea of what would be the market sentiment at various timeframes.

@Juanjacinto123 ,
I have updated the bot with the feature as requested. You can now specify multiple intervals with the TDPA_INTERVAL parameter. Default is set to '1h','3h' and '6h'.

Do note in the current setup, on the 3h mark it will send both '1h' and '3h' top pump pumps, and on the '6h' mark we will see the '1h', '3h' and '6h'. While it may be a little spammy, I believe the information from different timeframes is still insightful.

Give it a shot and let me know if there are any issues.

**Comment by Juanjacinto123** [comment]
> > Several values could also be configured for the ALERT_INTERVAL.
> > For example:
> > For the 12-hour reset interval, send the Tops alert for the last hour, the last 3h and the last 6h.
> > In this way we can have an idea of what would be the market sentiment at various timeframes.
> 
> @Juanjacinto123 ,
> I have updated the bot with the feature as requested. You can now specify multiple intervals with the TDPA_INTERVAL parameter. Default is set to '1h','3h' and '6h'.
> 
> Do note in the current setup, on the 3h mark it will send both '1h' and '3h' top pump pumps, and on the '6h' mark we will see the '1h', '3h' and '6h'. While it may be a little spammy, I believe the information from different timeframes is still insightful.
> 

.

I see that you modified the Bot so that the minimum time of each notification is the one corresponding to its respective Timeframe.

I think it is useful for very low time intervals, maybe less than 3m or 1m. 

But for larger intervals (say 15 minutes or 30 minutes) you lose a lot of alerts, because it would not notify again during those 15 or 30 minutes.

Perhaps you could leave an "automatic" notification mode, which would be the current mode, and a manual notification mode where the user decides the value of the notification interval, which would be in the mode we have been using.

Translated with www.DeepL.com/Translator (free version)

> Give it a shot and let me know if there are any issues.



> > Several values could also be configured for the ALERT_INTERVAL.
> > For example:
> > For the 12-hour reset interval, send the Tops alert for the last hour, the last 3h and the last 6h.
> > In this way we can have an idea of what would be the market sentiment at various timeframes.
> 
> @Juanjacinto123 ,
> I have updated the bot with the feature as requested. You can now specify multiple intervals with the TDPA_INTERVAL parameter. Default is set to '1h','3h' and '6h'.
> 
> Do note in the current setup, on the 3h mark it will send both '1h' and '3h' top pump pumps, and on the '6h' mark we will see the '1h', '3h' and '6h'. While it may be a little spammy, I believe the information from different timeframes is still insightful.
> 

Yes, I am testing it and I find it useful to send you the information of all Timeframes. 

The runtime update is also very useful.

> Give it a shot and let me know if there are any issues.

**Comment by Juanjacinto123** [comment]
I see that you modified the Bot so that the minimum time of each notification is the one corresponding to its respective Timeframe.

I think it is useful for very low time intervals, maybe less than 3m or 1m. 

But for larger intervals, which is my case (say 15 minutes or 30 minutes) you lose a lot of alerts, because it would not notify again during those 15 or 30 minutes.

Perhaps you could leave an "automatic" notification mode, which would be the current mode, and a manual notification mode where the user decides the value of the notification interval, which would be in the mode we have been using.

**Comment by Juanjacinto123** [comment]
> > Several values could also be configured for the ALERT_INTERVAL.
> > For example:
> > For the 12-hour reset interval, send the Tops alert for the last hour, the last 3h and the last 6h.
> > In this way we can have an idea of what would be the market sentiment at various timeframes.
> 
> @Juanjacinto123 ,
> I have updated the bot with the feature as requested. You can now specify multiple intervals with the TDPA_INTERVAL parameter. Default is set to '1h','3h' and '6h'.
> 
> Do note in the current setup, on the 3h mark it will send both '1h' and '3h' top pump pumps, and on the '6h' mark we will see the '1h', '3h' and '6h'. While it may be a little spammy, I believe the information from different timeframes is still insightful.
> 

Yes, I am testing it and I find it useful to send you the information of all Timeframes. 

The runtime update is also very useful.

> Give it a shot and let me know if there are any issues.

**Comment by Juanjacinto123** [comment]
After an hour of running, I received this error:

_Top 5 PUMP
AXSUSDT : 0.04959
ERNUSDT : 0.04371
CHRUSDT : 0.04328
FORTHUSDT : 0.04178
BTGUSDT : 0.03212
Top 5 DUMP
DNTUSDT : -0.03303
BELUSDT : -0.01007
EPSUSDT : -0.00584
DREPUSDT : -0.00472
KMDUSDT : -0.00396

Traceback (most recent call last):
  File ".\price_tracker.py", line 76, in <module>
    topPumpDump(tpda_last_trigger,full_data) # Triggers check for top_pump_dump
  File "C:\Users\flia\Documents\GitHub\binance-pump-top-24-7\binance-pump-alerts-master\functions.py", line 98, in topPumpDump
    pump_sorted_list = sorted(full_asset, key = lambda i: i[inter],reverse=True)[0:VIEW_NUMBER]
  File "C:\Users\flia\Documents\GitHub\binance-pump-top-24-7\binance-pump-alerts-master\functions.py", line 98, in <lambda>
    pump_sorted_list = sorted(full_asset, key = lambda i: i[inter],reverse=True)[0:VIEW_NUMBER]
KeyError: '1h'
PS C:\Users\flia\Documents\GitHub\binance-pump-top-24-7\binance-pump-alerts-master>_


This is my configuration for params.py:

# Main params
intervals = ['1m', '3m', '5m', '10m', '15m', '30m']
outlier_param = {'1m':0.015,'3m':0.02,'5m':0.03,'10m':0.03,'15m':0.03,'30m':0.04}
pairs_of_interest = ['USDT'] # Other options include 'BTC' , 'ETH'

# Useful Params
EXTRACT_INTERVAL = '30s'  # Interval between each price extract

# Optional Watchlist only mode
watchlist = []  # E.g. ['ADAUSDT', 'ETHUSDT'] # Note that if watchlist has pairs, ONLY pairs in watchlist will be monitored

# Feature params
FUTURE_ENABLED = False # Determine whether to look at future markets
DUMP_ENABLED = True # Determine whether to look at DUMP

# Top Pump & Dump Feature Params
TOP_PUMP_ENABLED = True # Set to false if not interested in top pump info
TOP_DUMP_ENABLED = True # Set to false if not interested in top dump info
VIEW_NUMBER = 5 # Top X amount of coins shown, adjust to show more or less within the timeframe
TDPA_INTERVALS = ['30m','1h'] # Intervals for top pump and dump to be sent, Ensure its in interval + outlier_param as well

# Debug Params (Avoid touching it if there's no issues)
PRINT_DEBUG = True # If false we do not print messages
RESET_INTERVAL = '6h' # Interval for clearing array to prevent MEM ERROR can handle up to 12h+ depending on system
GET_PRICE_FAIL_INTERVAL = '10s' # In the case of get price fail, this is the time delay before re-attempt
SEND_TELEGRAM_FAIL_INTERVAL = '5s' # If telegram message fails to send, this is the time delay before re-attempt

**Comment by brianleect** [comment]
> I see that you modified the Bot so that the minimum time of each notification is the one corresponding to its respective Timeframe.
> 
> I think it is useful for very low time intervals, maybe less than 3m or 1m.
> 
> But for larger intervals, which is my case (say 15 minutes or 30 minutes) you lose a lot of alerts, because it would not notify again during those 15 or 30 minutes.
> 
> Perhaps you could leave an "automatic" notification mode, which would be the current mode, and a manual notification mode where the user decides the value of the notification interval, which would be in the mode we have been using.

Regarding the new change, in theory it should not prevent triggering of earlier intervals. For example, if a trigger was set off for '30m', it is true that the '30m' trigger will not be set off until at least a time of 30m has passed. However, for earlier intervals such as '1m' , '5m', and '15m' for example, will not have any issues being triggered. (In theory at least) This implementation should only affect triggering of timeframes >= triggered interval. 

Do let me know if you see that smaller intervals are being blocked off due to the current implementation.

**Comment by brianleect** [comment]
> > > Several values could also be configured for the ALERT_INTERVAL.
> > > For example:
> > > For the 12-hour reset interval, send the Tops alert for the last hour, the last 3h and the last 6h.
> > > In this way we can have an idea of what would be the market sentiment at various timeframes.
> > 
> > 
> > @Juanjacinto123 ,
> > I have updated the bot with the feature as requested. You can now specify multiple intervals with the TDPA_INTERVAL parameter. Default is set to '1h','3h' and '6h'.
> > Do note in the current setup, on the 3h mark it will send both '1h' and '3h' top pump pumps, and on the '6h' mark we will see the '1h', '3h' and '6h'. While it may be a little spammy, I believe the information from different timeframes is still insightful.
> 
> Yes, I am testing it and I find it useful to send you the information of all Timeframes.
> 
> The runtime update is also very useful.
> 
> > Give it a shot and let me know if there are any issues.

Thanks for the feedback!

**Comment by brianleect** [comment]
> After an hour of running, I received this error:
> 
> _Top 5 PUMP
> AXSUSDT : 0.04959
> ERNUSDT : 0.04371
> CHRUSDT : 0.04328
> FORTHUSDT : 0.04178
> BTGUSDT : 0.03212
> Top 5 DUMP
> DNTUSDT : -0.03303
> BELUSDT : -0.01007
> EPSUSDT : -0.00584
> DREPUSDT : -0.00472
> KMDUSDT : -0.00396
> 
> Traceback (most recent call last):
> File ".\price_tracker.py", line 76, in
> topPumpDump(tpda_last_trigger,full_data) # Triggers check for top_pump_dump
> File "C:\Users\flia\Documents\GitHub\binance-pump-top-24-7\binance-pump-alerts-master\functions.py", line 98, in topPumpDump
> pump_sorted_list = sorted(full_asset, key = lambda i: i[inter],reverse=True)[0:VIEW_NUMBER]
> File "C:\Users\flia\Documents\GitHub\binance-pump-top-24-7\binance-pump-alerts-master\functions.py", line 98, in
> pump_sorted_list = sorted(full_asset, key = lambda i: i[inter],reverse=True)[0:VIEW_NUMBER]
> KeyError: '1h'
> PS C:\Users\flia\Documents\GitHub\binance-pump-top-24-7\binance-pump-alerts-master>_
> 
> This is my configuration for params.py:
> 
> Main params
> intervals = ['1m', '3m', '5m', '10m', '15m', '30m']
> outlier_param = {'1m':0.015,'3m':0.02,'5m':0.03,'10m':0.03,'15m':0.03,'30m':0.04}
> pairs_of_interest = ['USDT'] # Other options include 'BTC' , 'ETH'
> 
> Useful Params
> EXTRACT_INTERVAL = '30s' # Interval between each price extract
> 
> Optional Watchlist only mode
> watchlist = [] # E.g. ['ADAUSDT', 'ETHUSDT'] # Note that if watchlist has pairs, ONLY pairs in watchlist will be monitored
> 
> Feature params
> FUTURE_ENABLED = False # Determine whether to look at future markets
> DUMP_ENABLED = True # Determine whether to look at DUMP
> 
> Top Pump & Dump Feature Params
> TOP_PUMP_ENABLED = True # Set to false if not interested in top pump info
> TOP_DUMP_ENABLED = True # Set to false if not interested in top dump info
> VIEW_NUMBER = 5 # Top X amount of coins shown, adjust to show more or less within the timeframe
> TDPA_INTERVALS = ['30m','1h'] # Intervals for top pump and dump to be sent, Ensure its in interval + outlier_param as well
> 
> Debug Params (Avoid touching it if there's no issues)
> PRINT_DEBUG = True # If false we do not print messages
> RESET_INTERVAL = '6h' # Interval for clearing array to prevent MEM ERROR can handle up to 12h+ depending on system
> GET_PRICE_FAIL_INTERVAL = '10s' # In the case of get price fail, this is the time delay before re-attempt
> SEND_TELEGRAM_FAIL_INTERVAL = '5s' # If telegram message fails to send, this is the time delay before re-attempt

Regarding this error, the current model requires the interval to be part of the intervals to be able to send the top pump info. 

Key error '1h' was triggered as your current interval array does not contain it. A quick fix would be to add '1h' in the interval array and the outlier_param array as well, possibly with a large value if you do not wish for it to trigger.

I'll try to see if I can modify the code such that the top pump and dump alerts is able to work without dependence on % change interval. For now the solution I mentioned above would be a good fix.

**Comment by Juanjacinto123** [comment]
> > I see that you modified the Bot so that the minimum time of each notification is the one corresponding to its respective Timeframe.
> > I think it is useful for very low time intervals, maybe less than 3m or 1m.
> > But for larger intervals, which is my case (say 15 minutes or 30 minutes) you lose a lot of alerts, because it would not notify again during those 15 or 30 minutes.
> > Perhaps you could leave an "automatic" notification mode, which would be the current mode, and a manual notification mode where the user decides the value of the notification interval, which would be in the mode we have been using.
> 
> Regarding the new change, in theory it should not prevent triggering of earlier intervals. For example, if a trigger was set off for '30m', it is true that the '30m' trigger will not be set off until at least a time of 30m has passed. However, for earlier intervals such as '1m' , '5m', and '15m' for example, will not have any issues being triggered. (In theory at least) This implementation should only affect triggering of timeframes >= triggered interval.
> 
> Do let me know if you see that smaller intervals are being blocked off due to the current implementation.



> > I see that you modified the Bot so that the minimum time of each notification is the one corresponding to its respective Timeframe.
> > I think it is useful for very low time intervals, maybe less than 3m or 1m.
> > But for larger intervals, which is my case (say 15 minutes or 30 minutes) you lose a lot of alerts, because it would not notify again during those 15 or 30 minutes.
> > Perhaps you could leave an "automatic" notification mode, which would be the current mode, and a manual notification mode where the user decides the value of the notification interval, which would be in the mode we have been using.
> 
> Regarding the new change, in theory it should not prevent triggering of earlier intervals. For example, if a trigger was set off for '30m', it is true that the '30m' trigger will not be set off until at least a time of 30m has passed. However, for earlier intervals such as '1m' , '5m', and '15m' for example, will not have any issues being triggered. (In theory at least) This implementation should only affect triggering of timeframes >= triggered interval.
> 

I understand, but it seemed to me more functional with the previous mode due to the fact that the user can choose the period of silence.

For example I monitor notifications every 1m for changes greater than 4.5% in the 30m temporality. In most cases that change exceeds that 4.5% and may reach 6.5%, so for a few minutes after the first trigger, the 30m alert continues notifying (in my case the bigger the change is much better, because I operate the correction)... This is why I tell you that in the new mode you lose better opportunities to enter the market.

However, if it is too complicated to re-activate it, I can use the last version of the Bot in which it worked.

> Do let me know if you see that smaller intervals are being blocked off due to the current implementation.

There is no problem with minor intervals.

**Comment by Juanjacinto123** [comment]
> > After an hour of running, I received this error:
> > _Top 5 PUMP
> > AXSUSDT : 0.04959
> > ERNUSDT : 0.04371
> > CHRUSDT : 0.04328
> > FORTHUSDT : 0.04178
> > BTGUSDT : 0.03212
> > Top 5 DUMP
> > DNTUSDT : -0.03303
> > BELUSDT : -0.01007
> > EPSUSDT : -0.00584
> > DREPUSDT : -0.00472
> > KMDUSDT : -0.00396
> > Traceback (most recent call last):
> > File ".\price_tracker.py", line 76, in
> > topPumpDump(tpda_last_trigger,full_data) # Triggers check for top_pump_dump
> > File "C:\Users\flia\Documents\GitHub\binance-pump-top-24-7\binance-pump-alerts-master\functions.py", line 98, in topPumpDump
> > pump_sorted_list = sorted(full_asset, key = lambda i: i[inter],reverse=True)[0:VIEW_NUMBER]
> > File "C:\Users\flia\Documents\GitHub\binance-pump-top-24-7\binance-pump-alerts-master\functions.py", line 98, in
> > pump_sorted_list = sorted(full_asset, key = lambda i: i[inter],reverse=True)[0:VIEW_NUMBER]
> > KeyError: '1h'
> > PS C:\Users\flia\Documents\GitHub\binance-pump-top-24-7\binance-pump-alerts-master>_
> > This is my configuration for params.py:
> > Main params
> > intervals = ['1m', '3m', '5m', '10m', '15m', '30m']
> > outlier_param = {'1m':0.015,'3m':0.02,'5m':0.03,'10m':0.03,'15m':0.03,'30m':0.04}
> > pairs_of_interest = ['USDT'] # Other options include 'BTC' , 'ETH'
> > Useful Params
> > EXTRACT_INTERVAL = '30s' # Interval between each price extract
> > Optional Watchlist only mode
> > watchlist = [] # E.g. ['ADAUSDT', 'ETHUSDT'] # Note that if watchlist has pairs, ONLY pairs in watchlist will be monitored
> > Feature params
> > FUTURE_ENABLED = False # Determine whether to look at future markets
> > DUMP_ENABLED = True # Determine whether to look at DUMP
> > Top Pump & Dump Feature Params
> > TOP_PUMP_ENABLED = True # Set to false if not interested in top pump info
> > TOP_DUMP_ENABLED = True # Set to false if not interested in top dump info
> > VIEW_NUMBER = 5 # Top X amount of coins shown, adjust to show more or less within the timeframe
> > TDPA_INTERVALS = ['30m','1h'] # Intervals for top pump and dump to be sent, Ensure its in interval + outlier_param as well
> > Debug Params (Avoid touching it if there's no issues)
> > PRINT_DEBUG = True # If false we do not print messages
> > RESET_INTERVAL = '6h' # Interval for clearing array to prevent MEM ERROR can handle up to 12h+ depending on system
> > GET_PRICE_FAIL_INTERVAL = '10s' # In the case of get price fail, this is the time delay before re-attempt
> > SEND_TELEGRAM_FAIL_INTERVAL = '5s' # If telegram message fails to send, this is the time delay before re-attempt
> 
> Regarding this error, the current model requires the interval to be part of the intervals to be able to send the top pump info.
> 
> Key error '1h' was triggered as your current interval array does not contain it. A quick fix would be to add '1h' in the interval array and the outlier_param array as well, possibly with a large value if you do not wish for it to trigger.
> 
> Example
> intervals = ['1m', '3m', '5m', '10m', '15m', '30m','1h']
> outlier_param = {'1m':0.015,'3m':0.02,'5m':0.03,'10m':0.03,'15m':0.03,'30m':0.04,'1h':0.10}
> 
> I'll try to see if I can modify the code such that the top pump and dump alerts is able to work without dependence on % change interval. For now the solution I mentioned above would be a good fix.

Yes, you are absolutely right, I had not noticed that detail. 

Thanks for clarifying.

**Comment by brianleect** [comment]
> I understand, but it seemed to me more functional with the previous mode due to the fact that the user can choose the period of silence.
> 
> For example I monitor notifications every 1m for changes greater than 4.5% in the 30m temporality. In most cases that change exceeds that 4.5% and may reach 6.5%, so for a few minutes after the first trigger, the 30m alert continues notifying (in my case the bigger the change is much better, because I operate the correction)... This is why I tell you that in the new mode you lose better opportunities to enter the market.
> 
> However, if it is too complicated to re-activate it, I can use the last version of the Bot in which it worked.
> 
> > Do let me know if you see that smaller intervals are being blocked off due to the current implementation.
> 
> There is no problem with minor intervals.

I have re-introduced the legacy parameter MIN_ALERT_INTERVAL. However, I have made it to be disabled by default. You can enable it by setting HARD_ALERT_INTERVAL_ENABLED to False and setting MIN_ALERT_INTERVAL to your preferred value.

Thanks for the clarification @Juanjacinto123 !

**Comment by Juanjacinto123** [comment]
> > I understand, but it seemed to me more functional with the previous mode due to the fact that the user can choose the period of silence.
> > For example I monitor notifications every 1m for changes greater than 4.5% in the 30m temporality. In most cases that change exceeds that 4.5% and may reach 6.5%, so for a few minutes after the first trigger, the 30m alert continues notifying (in my case the bigger the change is much better, because I operate the correction)... This is why I tell you that in the new mode you lose better opportunities to enter the market.
> > However, if it is too complicated to re-activate it, I can use the last version of the Bot in which it worked.
> > > Do let me know if you see that smaller intervals are being blocked off due to the current implementation.
> > 
> > 
> > There is no problem with minor intervals.
> 
> I have re-introduced the legacy parameter MIN_ALERT_INTERVAL. However, I have made it to be disabled by default. You can enable it by setting HARD_ALERT_INTERVAL_ENABLED to False and setting MIN_ALERT_INTERVAL to your preferred value.
> 
> Thanks for the clarification @Juanjacinto123 !

Hi Brian, I was trying this latest update you made and apparently it does not activate correctly, because it keeps muting the alerts. 

I keep getting the message: 

Duration insufficient FETUSDT 10m
Duration insufficient ANKRUSDT 15m
Duration insufficient COCOSUSDT 1h

This is the configuration I currently have:

# Main params
intervals = ['1m', '3m', '5m', '10m', '15m', '30m', '1h']
outlier_param = {'1m':0.015,'3m':0.02,'5m':0.025,'10m':0.03,'15m':0.035,'30m':0.05,'1h':0.075}
pairs_of_interest = ['USDT'] # Other options include 'BTC' , 'ETH'

# Useful Params
EXTRACT_INTERVAL = '60s'  # Interval between each price extract

# Alert Interval Params
HARD_ALERT_INTERVAL_ENABLED = False # If set to true, if '5m' is triggered, any interval >= '5m' will rest for '5m' before triggering
MIN_ALERT_INTERVAL = '2m' # Minimum interval between each Alert  # Only will be utlized when HARD_ALERT_INTERVAL is False. 

# Optional Watchlist only mode
watchlist = []  # E.g. ['ADAUSDT', 'ETHUSDT'] # Note that if watchlist has pairs, ONLY pairs in watchlist will be monitored

# Feature params
FUTURE_ENABLED = False # Determine whether to look at future markets
DUMP_ENABLED = True # Determine whether to look at DUMP

# Top Pump & Dump Feature Params
TOP_PUMP_ENABLED = True # Set to false if not interested in top pump info
TOP_DUMP_ENABLED = True # Set to false if not interested in top dump info
VIEW_NUMBER = 5 # Top X amount of coins shown, adjust to show more or less within the timeframe
TDPA_INTERVALS = ['30m','1h'] # Intervals for top pump and dump to be sent, Ensure its in interval + outlier_param as well

# Debug Params (Avoid touching it if there's no issues)
PRINT_DEBUG = True # If false we do not print messages
RESET_INTERVAL = '12h' # Interval for clearing array to prevent MEM ERROR can handle up to 12h+ depending on system
GET_PRICE_FAIL_INTERVAL = '5s' # In the case of get price fail, this is the time delay before re-attempt
SEND_TELEGRAM_FAIL_INTERVAL = '3s' # If telegram message fails to send, this is the time delay before re-attempt

**Comment by brianleect** [comment]
Thanks for the update @Juanjacinto123 , I might have made a mistake in the conditional chain. 

I suspect the problem to lie at at line 71 for functions where the code enters the conditional for HARD_ALERT_INTERVQL when it's supposed to ignore it. 

I'll fix it in a bit!

**Comment by brianleect** [comment]
@Juanjacinto123 , you can check the updated version. The problem should be solved.

**Comment by Juanjacinto123** [comment]
> @Juanjacinto123 , you can check the updated version. The problem should be solved.

Thanks Brian, so far it is working fine

**Comment by brianleect** [comment]
Closing as no issues and feature has been implemented.
