### ISSUE TITLE
[Possible Feature] Individualized Outlier Params

### ISSUE THREAD

**Issue by brianleect** [brianleect/binance-pump-alerts#17]
Could consider setting individual trigger params for pairs of concern e.g. for BTC or ETH we could have lower trigger params we wish to customize.

Will consider implementing if there's enough interest.

**Comment by patbaumgartner** [comment]
Why not running multiple instances of the app? One for lower trigger params and one for the higher ones?

my2cents: The proposed approach keeps the current implementation simple and adds not too much clutter.

**Comment by brianleect** [comment]
Currently feature does not seem especially important. Suggestion by @patbaumgartner seems sufficient for now. Will reopen issue if we see a need for it.
