### ISSUE TITLE
[Bug] 0% Top Pump Dump Alerts

### ISSUE THREAD

**Issue by brianleect** [brianleect/binance-pump-alerts#18]
There might also be a possible bug where we attempt to send an alert after a recent reset has been triggered. I have yet to test this case. In theory it would end up sending a message with all change being 0% due to the lack of data points.

_Originally posted by @brianleect in https://github.com/brianleect/binance-pump-alerts/issues/16#issuecomment-884713654_

**Comment by brianleect** [comment]
![image](https://user-images.githubusercontent.com/63389110/126737994-2765dfc5-dd2e-4009-9d6c-0afb9109a9a8.png)

Suspicions were true, first trigger ended up being all 0%.

Possible fix: Add a larger time gap before the initial trigger?

**Comment by brianleect** [comment]
Fixed by widening 1s buffer to 3s additional buffer.

**Comment by brianleect** [comment]
Apparently not fully solved. Buffer does not consistently seem to work.

'3h' interval fails with current buffer at 5s

However the buffer seems to work for 15m interval.

Not sure what is causing this issue.

**Comment by brianleect** [comment]
Possible solution is the have a variable buffer set to a minimum of '5s' and max of 0.5%.

Alternatively, we can have the first TDPA to always be triggered only after X minutes? This should fully solve the problem actually

**Comment by brianleect** [comment]
Fixed with latest bug fix which adds a '5m' buffer to initial TDPA

**Comment by brianleect** [comment]
Problem re-introduced with latest merge. '1s' buffer does not seem to fix it. 

![image](https://user-images.githubusercontent.com/63389110/129658007-314b08f0-9da3-4b1f-8f3d-4f32704fd08d.png)
![image](https://user-images.githubusercontent.com/63389110/129658018-e994b2d9-e02c-4b41-9bc8-7d5b4355925c.png)

**Comment by patbaumgartner** [comment]
This is still the case with the current implementation. It looks like working mainly with only seconds and not fractions did not help fully. Need to investigate more.
