### ISSUE TITLE
[Minor Bug] Newly listed coins

### ISSUE THREAD

**Issue by brianleect** [brianleect/binance-pump-alerts#21]
Due to how the program is currently structured, it only initializes the coin array once. Assuming we run the program for an extended period of time it is likely to not consider new pairs that are introduced.

Potential Solution
1. On each run we check length of price data. (If it changes from the prior length) we either 
1a. Re-initialize the entire array (simple but inefficient sol resulting in loss of price data as well) 
1b. Identify new pairs and initialize them into the current array (Slightly more effort but should be simple still)

**Comment by brianleect** [comment]
Fix uploaded to dev branch, will be running it to see if it works

**Comment by brianleect** [comment]
![image](https://user-images.githubusercontent.com/63389110/128489886-ae0df146-384e-486d-802e-ae73303043da.png)

Seems to have detected new pairs and continued running with any issue.

**Comment by brianleect** [comment]
Will close once it's tested to be working again

**Comment by patbaumgartner** [comment]
Are you not going to add a news emoji for this kind of thing? makes it just
easier to read if the spacing is all the same. )

**Comment by brianleect** [comment]
> Are you not going to add a news emoji for this kind of thing? makes it just easier to read if the spacing is all the same. )
> […](#)

Good idea. I have simplified the message as well.

![image](https://user-images.githubusercontent.com/63389110/128497080-55a65d05-4f46-4bb9-88a5-1fbcec9b6d61.png)

**Comment by brianleect** [comment]
Found a bug related to listing detection as well, which I'll sync with the master branch once I verify its working

**Comment by brianleect** [comment]
![image](https://user-images.githubusercontent.com/63389110/128498274-439c5ca1-1efe-4e51-92a9-ffd8a9871000.png)

Bug mentioned, introduced due to checkNewListing initialization not being compatible to new spam reduction update.

Should be fixed by the newest update.

**Comment by brianleect** [comment]
Closed as detection and tracking of newly listed pairs has no issues.
