### ISSUE TITLE
[Discussion] [Improvement] Overall market state

### ISSUE THREAD

**Issue by brianleect** [brianleect/binance-pump-alerts#22]
In scheduled TDPA, instead of just top pump and dumped coins some other possibly insightful values could be added such as

1. Average % change in price for each coin
2. Net coins up / Net coins down

Would be an interesting piece of information to be sent along with top X dump and pump coins.

Implementation should not be too difficult. Will try to implement within 1-2 weeks or sooner if I can find the time.

I'm open to implementing other metrics as well, feel free to comment any interesting ideas.

**Comment by Juanjacinto123** [comment]
> In scheduled TDPA, instead of just top pump and dumped coins some other possibly insightful values could be added such as
> 
> 1. Average % change in price for each coin
> 2. Net coins up / Net coins down
> 
> Would be an interesting piece of information to be sent along with top X dump and pump coins.
> 
> Implementation should not be too difficult. Will try to implement within 1-2 weeks or sooner if I can find the time.
> 
> I'm open to implementing other metrics as well, feel free to comment any interesting ideas.


Hi @brianleect, 

An alert can be created that represents the current market sentiment. 

With a simple summation between all currencies with positive average and all currencies with negative average, one would have a slight idea of the market trend. If the result of the summation is >0 the sentiment would be bullish, if <0 the sentiment would be bearish.

Of course this is just a very basic idea that comes to mind. But you could look for a better elaborated formula that represents the trend based on some sort of scale.

For example:

-Medium bullish trend. 

-Slightly bullish trend. 

-Neutral trend. 

-Slightly downward trend. 

-Moderately bearish trend. 

This new alert can be optional and would be sent at user-defined time intervals, as is done with the "Top Dump" and "Top Pump" for both the Spot and Futures markets.

**Comment by brianleect** [comment]
> > In scheduled TDPA, instead of just top pump and dumped coins some other possibly insightful values could be added such as
> > 
> > 1. Average % change in price for each coin
> > 2. Net coins up / Net coins down
> > 
> > Would be an interesting piece of information to be sent along with top X dump and pump coins.
> > Implementation should not be too difficult. Will try to implement within 1-2 weeks or sooner if I can find the time.
> > I'm open to implementing other metrics as well, feel free to comment any interesting ideas.
> 
> Hi @brianleect,
> 
> An alert can be created that represents the current market sentiment.
> 
> With a simple summation between all currencies with positive average and all currencies with negative average, one would have a slight idea of the market trend. If the result of the summation is >0 the sentiment would be bullish, if <0 the sentiment would be bearish.
> 
> Of course this is just a very basic idea that comes to mind. But you could look for a better elaborated formula that represents the trend based on some sort of scale.
> 
> For example:
> 
> -Medium bullish trend.
> 
> -Slightly bullish trend.
> 
> -Neutral trend.
> 
> -Slightly downward trend.
> 
> -Moderately bearish trend.
> 
> This new alert can be optional and would be sent at user-defined time intervals, as is done with the "Top Dump" and "Top Pump" for both the Spot and Futures markets.

Thanks for the input @Juanjacinto123 , an overall trend sounds interesting and a simple version could likely be done just based on summation as you mentioned.
