### ISSUE TITLE
[Feature Request] Making param names consistent

### ISSUE THREAD

**Issue by patbaumgartner** [brianleect/binance-pump-alerts#35]
In params.py the first params are written lower case whereas other params are written UPPER_CASE. I would love to adjust the Dockerfile for all params in the same way. Therefore it would be great to have all the params written in the same way. WDYT? Is there a specific reason?

Best,
Patrick

**Comment by brianleect** [comment]
> In params.py the first params are written lower case whereas other params are written UPPER_CASE. I would love to adjust the Dockerfile for all params in the same way. Therefore it would be great to have all the params written in the same way. WDYT? Is there a specific reason?
> 
> Best,
> Patrick

Ah the initial params were lowercase due to bad implementation on my part. Started changing to CAPS convention later on.

Yep we should change it all to CAPS.

**Comment by patbaumgartner** [comment]
Can we move it maybe into a property or even a yaml file? Since it is configuration?

**Comment by brianleect** [comment]
> Can we move it maybe into a property or even a yaml file? Since it is configuration?

We could move it. However, I'm not familiar with the setting up the property / yaml file.

**Comment by brianleect** [comment]
Alternatively we could just rename the current non-cap parameters to CAPs.

**Comment by patbaumgartner** [comment]
I could create a pull-request and playing a bit with it. Want me to make a
suggestion?
