### ISSUE TITLE
[Major] [Rework] Telegram Message sending

### ISSUE THREAD

**Issue by brianleect** [brianleect/binance-pump-alerts#42]
Look into co-routines / async / threading implementation for telegram messages.

Current model sleeps on a failed message which stops the entire program and impacts the price extraction process. Not optimal and might be give off false alerts.

**Comment by brianleect** [comment]
![image](https://user-images.githubusercontent.com/63389110/129690345-8b0660d7-27bf-44ab-8d34-c696c73242b2.png)

20-30 Dump messages within a minute. While it is caused by ETH dumping, I suspect the delay in the main thread caused by the tele message may have resulted in a 3s or 4s actual price movement while it is only recorded as 1s resulting in large amount of alerts.

**Comment by brianleect** [comment]
A possible alternative is similar to summarized alerts, we can have messages all combined into a single string to be sent.

So on a major movement down resulting in 20-30 alts dumping >=2% within a second we would send this as a SINGLE message.

This would reduce time held up by telegram message and also possibly spam?

Best fix is still to implement threading. Will see if I can get it done by the end of this week hopefully.

**Comment by brianleect** [comment]
Latest PR should have solved the issue. Leaving the link below for reference on multi-threading implemented within the library.

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Performance-Optimizations

**Comment by brianleect** [comment]
![image](https://user-images.githubusercontent.com/63389110/129901671-8cb43abc-6b5a-484f-b55e-46dbd75bc404.png)

Issue with latest PR, not sure if error is only specific to ec2.

**Comment by brianleect** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/issues/877

Could look into using async rather than threads.

**Comment by patbaumgartner** [comment]
ThreadExecutor is faster than async or coroutines, and simpler to setup. Anyhow we have set max-threads to 30, we can also set them to 5. no issues

**Comment by brianleect** [comment]
> ThreadExecutor is faster than async or coroutines, and simpler to setup. Anyhow we have set max-threads to 30, we can also set them to 5. no issues

Alright, I'll try setting it to 5 on the aws ec2 server and see if the issue still occurs. 

I was originally thinking of possibly just having a single thread dedicated to sending telegram messages, since the key aim is to not hold up the main program. But if 5 thread setup works too that would be good as well.

**Comment by brianleect** [comment]
https://github.com/brianleect/binance-pump-alerts/issues/47

Closing as issue resolved. Out of memory was an aws ec2 issue. Feature seems to be working as intended.
