### ISSUE TITLE
[Bug] P&D Alerts

### ISSUE THREAD

**Issue by brianleect** [brianleect/binance-pump-alerts#45]
![image](https://user-images.githubusercontent.com/63389110/129603927-9e9c1ab8-5365-48c9-8dc5-2a08f9ce9b9f.png)

Outlier params
![image](https://user-images.githubusercontent.com/63389110/129603981-cdc61920-c525-46ca-8d2a-f1f635a03474.png)

Shouldn't be seeing a trigger of -0.5% when the minimum is 2%.

**Comment by brianleect** [comment]
Will continue running newest version and see if the problem re-occurs.

**Comment by brianleect** [comment]
Unable to replicate atm. Will leave the script running for further duration for monitoring.

**Comment by brianleect** [comment]
![image](https://user-images.githubusercontent.com/63389110/129729394-9b60d986-e305-43dc-af40-da58836e1eeb.png)

Another weird issue. Might be due to the way telegram message is modelled.

**Comment by brianleect** [comment]
7 alerts received on main BPA tele for old version vs 120 alerts on new version.

Something is clearly off.

**Comment by patbaumgartner** [comment]
maybe some adjustments in the threshold are needed? -> At least I changed the format of the message already :) did not spot that yet.

**Comment by brianleect** [comment]
> maybe some adjustments in the threshold are needed? -> At least I changed the format of the message already :) did not spot that yet.

Yep. Haven't been able to replicate it again. Was previously using default configurations. 

I'll close this for now unless I get the error again.
