### ISSUE TITLE
[Bug] Aws Ec2 Killed

### ISSUE THREAD

**Issue by brianleect** [brianleect/binance-pump-alerts#47]
![image](https://user-images.githubusercontent.com/63389110/129821628-e46c29fa-eb5b-4e7c-95c3-384fd111da42.png)

Issue only faced in latest version. Not sure what is causing it. Not sure if this error is specific to ec2 as well or occurs for other machines running for extended duration.

Duration: ~30+ Hours

Will see if i can replicate this error again.

**Comment by brianleect** [comment]
https://stackoverflow.com/questions/64602324/i-am-using-t2-micro-ec2-instance-it-goes-out-of-memory-and-kills-the-process-an

https://stackoverflow.com/questions/49440125/getting-killed-error-in-aws-but-works-in-mac

Not sure if it's a RAM issue related to the ec2.

**Comment by brianleect** [comment]
Might be a thread issue. Reduced total thread to 3. Hopefully fixes the problem.

Might consider setting only 1 separate thread to handle telegram messages alternatively if 3 total thread fails.

**Comment by brianleect** [comment]
![image](https://user-images.githubusercontent.com/63389110/130196130-1df14202-c205-4fd8-b33d-f12b1babe267.png)

Original stable version got killed as well. This occurred after running the other version with 3 thread executors. Might be aws ec2 limitation.

Will try re-running it and see if the problem re-occurs.

**Comment by patbaumgartner** [comment]
Might be an issue with EC2 with long-running apps/threads. 

Probably running out of memory - https://serverfault.com/questions/268288/most-long-running-commands-instantly-killed-on-amazon-ec2-ubuntu-10-04

**Comment by brianleect** [comment]
Closing for now, main issue was indeed limitation for aws ec2 memory. 3 max workers atm should not be an issue for most machines.

Will re-open if other users face an issue with this change. Possible alternative is change to 1? (Not sure if this would have any issues)
