### ISSUE TITLE
Volume Mappings Docker

### ISSUE THREAD

**Issue by blckwhtx** [brianleect/binance-pump-alerts#59]
can I somehow assign the path myself for my docker setup

volumes:
- /path/to/appdata/config.yml:/config.yml

**Comment by patbaumgartner** [comment]
Can't you just map the file into the container? Or use environment variables to pass to manipulate the config file?

**Comment by blckwhtx** [comment]
I just wanted to know if mapping is possible because I want my config.yml in a different location, I have Ubuntu server without ui and for testing I mount it on an extra drive where I can make quick changes

**Comment by blckwhtx** [comment]
- /path/to/appdata/config.yml:/config.yml




Would it be so right

**Comment by patbaumgartner** [comment]
just map it to /binance-pump-alerts/config.xml into the container.

**Comment by blckwhtx** [comment]
ok everything works, thanks
