### ISSUE TITLE
Spam alerts during a pump

### ISSUE THREAD

**Issue by brianleect** [brianleect/binance-pump-alerts#6]
Due to how checks are done, which is comparing a price point against a number of previous data point for each interval, we have repeated alerts within a short span.

![image](https://user-images.githubusercontent.com/63389110/124097920-a007a980-da8e-11eb-944a-692ac1531f57.png)

Possible solution
1. Implement auto sleep for x amount of seconds for alert (But it might result in missing out pumps that might be occurring at the same time)

**Comment by brianleect** [comment]
Temporarily solved by reducing number of intervals. Considering the short-lived nature of pumps removing the '5m' interval actually solves the issue of spam while still fulfilling the role of detecting pumps.

**Comment by Juanjacinto123** [comment]
> Temporarily solved by reducing number of intervals. Considering the short-lived nature of pumps removing the '5m' interval actually solves the issue of spam while still fulfilling the role of detecting pumps.

To avoid spam in the notifications, each of these could be muted for different periods of time chosen by the user. For example; muted for 5 minutes, 15 minutes, 30 minutes, etc.

This would be an interesting feature that can be implemented optionally.

**Comment by brianleect** [comment]
Thanks @Juanjacinto123 , I'll reopen the issue for now. Would have to rework some portions of the code to get it up.

**Comment by brianleect** [comment]
> > Temporarily solved by reducing number of intervals. Considering the short-lived nature of pumps removing the '5m' interval actually solves the issue of spam while still fulfilling the role of detecting pumps.
> 
> HI @brianleect,
> 
> To avoid spam in the notifications, each of these could be muted for different periods of time chosen by the user. For example; muted for 5 minutes, 15 minutes, 30 minutes, etc.
> 
> This would be an interesting feature that can be implemented optionally.

I have implemented this feature under the parameter 'MIN_ALERT_INTERVAL' , it has yet to be fully tested but it should work theoretically. Thanks for the input @Juanjacinto123 ! I'll close the issue once it is determined to be fully working.

**Comment by brianleect** [comment]
Closing as no issues regarding spam occurred thus far.
