### ISSUE TITLE
Todo: Integrate with Binance API to make trades on pumps.

### ISSUE THREAD

**Issue by blckwhtx** [brianleect/binance-pump-alerts#60]
it would also be possible to transfer the buy signal to another trading bot. for example freqtrade (https://www.freqtrade.io/en/stable/)

with --> "/forcebuy BTC/USDT"

and everything else is done via the strategy or config with stoploss, trailing stoploss and what profit take away

**Comment by patbaumgartner** [comment]
Why not implement your own freqtrade strategy which buys the stuff according to the rules implemented there? I have written my own algorithms in freqtrade already and I would integrate it there and not with our tool.

Can you please close the issue?

**Comment by blckwhtx** [comment]
war nur eine idee, mehr auch nicht
