### ISSUE TITLE
[Possible Feature] Exclusion of a specific cryptocurrency from the watch list

### ISSUE THREAD

**Issue by Juanjacinto123** [brianleect/binance-pump-alerts#63]
A pleasure to greet you again @brianleect,

I would like to suggest that specific pairs could be excluded from the watch list. 

For example, if out of a total of 140 pairs I want to exclude 5 pairs, it is more practical to exclude only those 5 pairs, than to have to manually add 135 pairs to the watch list. 

It would be something like:

# Exclusion mode, if enabled, pairs in this list will not be monitored.
# For example, 'ADAUSDT', 'ETHUSDT'.
# Exclusion list:
# - ADAUSDT
# - ETHUSDT

Thanks in advance as always.

**Comment by Juanjacinto123** [comment]
Hi Patrick, any idea on this matter? @patbaumgartner

**Comment by brianleect** [comment]
@Juanjacinto123 I have made a PR for this feature.

Try it out and let me know if you face any issues. I'll merge it to master if there's no issues in 1-2 weeks.

https://github.com/brianleect/binance-pump-alerts/tree/blacklist
^ Branch with the blacklist feature.

**Comment by Juanjacinto123** [comment]
> @Juanjacinto123 I have made a PR for this feature.
> 
> Try it out and let me know if you face any issues. I'll merge it to master if there's no issues in 1-2 weeks.
> 
> https://github.com/brianleect/binance-pump-alerts/tree/blacklist ^ Branch with the blacklist feature.

So far it works perfectly

**Comment by brianleect** [comment]
@Juanjacinto123 Any issues so far?

**Comment by Juanjacinto123** [comment]
> @Juanjacinto123 Any issues so far?

No problems so far, everything running perfectly

**Comment by brianleect** [comment]
Great to hear! I'll be closing the issue and merging the branch then.
