### ISSUE TITLE
Request Futures Api 

### ISSUE THREAD

**Issue by Juanjacinto123** [brianleect/binance-pump-alerts#7]
Could an option be added to choose between the Spot Market and the Binance Futures Market? I guess it would be a matter of alternating between the two Api. Thanks

**Comment by brianleect** [comment]
Have added the feature as requested. You can access it under params.py and changing the variable FUTURE_ENABLED to be false.

Let me know if you have any issues!

**Comment by brianleect** [comment]
Closing as feature has already been added. No further issues.
