### ISSUE TITLE
cant run the bot

### ISSUE THREAD

**Issue by yasserdzx** [brianleect/binance-pump-alerts#71]
Traceback (most recent call last):
  File "/Users/yasserben/Desktop/b3/pumpAlerts.py", line 92, in <module>
    main()
  File "/Users/yasserben/Desktop/b3/pumpAlerts.py", line 47, in main
    token=config["55348167:AAGtp0fcHhmWAy8cam7yu2yXQUdUk-8u_ww"],
KeyError: '55383467:AAGtp0fcHhmWAy8cam7yu2yXQUdUk-8u_ww'

**Comment by brianleect** [comment]
@yasserdzx 

Can you double check that your telegram token is correct? 

Also just to check, did you modify anything else outside of config.yml?

**Comment by yasserdzx** [comment]
telegram = TelegramSender(
        token=config["telegramToken"],
        chat_id=config["telegramChatId"],
i need to modify those two variables right ? 
the first one for the token 
the second is the chat id 
correct ?

**Comment by yasserdzx** [comment]
and which file should i include in ?

**Comment by yasserdzx** [comment]
thanks everything is working fine

**Comment by yasserdzx** [comment]
but am not recieving any alerts !!

**Comment by brianleect** [comment]
Did you specify the telegram group which you are sending to properly?

If you did you should receive an alert on start.
