### ISSUE TITLE
Other exchange

### ISSUE THREAD

**Issue by sergeypushckin2018** [brianleect/binance-pump-alerts#78]
Hello, have you ever thought about adapting the project to other exchanges or making some kind of general constructor through which it could be adapted to other exchanges?A little does not apply to the project, because it is on the binance, but I do not know where else it can be discussed

For example, I tried to put it on bybit now, but it doesn't work, I took this parameter as an url "https://api.bybit.com/spot/quote/v1/ticker/price " and the response to the request is a little different:
`{"ret_code":0,"ret_msg":"","result":[{"symbol":"WEMIXUSDT","price":"1.7165"},{"symbol":"HEROUSDT","price":"0.005061"},{"symbol":"INSURUSDT","price":"0.08254"},.....` there is no time parameter as on binance and the beginning is also a little different, but the symbol and price are the same as binance.

And here are the errors that gave me:
`  [2023-03-17 17:50:41,495] MainProcess  MainThread              INFO     binance-pump-alerts-app Using config file: config.yml
  [2023-03-17 17:50:41,495] MainProcess  MainThread              INFO     pump-and-dump-alerter   Nearest hour is 559 seconds away
Traceback (most recent call last):
  File "/home/qwe/bybit-pump-alerts/pumpAlerts.py", line 92, in <module>
    main()
  File "/home/qwe/bybit-pump-alerts/pumpAlerts.py", line 88, in main
    alerter.run()
  File "/home/qwe/bybit-pump-alerts/alerter/BinancePumpAndDumpAlerter.py", line 339, in run
    filtered_assets = self.filter_and_convert_assets(
  File "/home/qwe/bybit-pump-alerts/alerter/BinancePumpAndDumpAlerter.py", line 157, in filter_and_convert_assets
    symbol = exchange_asset["symbol"]
TypeError: string indices must be integers
`
Can you help solve the problem?

**Comment by brianleect** [comment]
Hi sergey thanks for the interest, sadly this project is scoped to being an easy setup for Binance and there are no plans to branch out to build it in a generalized manner due to exchange quirks on schema / unique pair types. 

https://github.com/ccxt/ccxt might be of interest to you but the setup might be a little more of a hassle
