### ISSUE TITLE
Some errors in the terminal

### ISSUE THREAD

**Issue by sergeypushckin2018** [brianleect/binance-pump-alerts#79]
I installed it on the VPS and noticed these messages
![Screenshot_3](https://user-images.githubusercontent.com/125546061/226493828-9f55eae3-bdc7-499f-9529-487617517a18.png)
![image](https://user-images.githubusercontent.com/125546061/226493925-caa5d88e-fc8c-4789-b990-2e0735d017d9.png)
![image](https://user-images.githubusercontent.com/125546061/226493961-bb94766d-61d6-4d07-8fc3-7cccde4b8064.png)
The log with errors in the screenshots is not complete, the beginning and the end only, after the messages the program continues to work, what is the problem I don't understand, maybe the VPS is weak?The bot works fine on a laptop

**Comment by sergeypushckin2018** [comment]
I think it's because of the vps server

**Comment by brianleect** [comment]
Odds are it's likely a connectivity issue with the VPS. I suppose an alternative soln would be have some handling in the case where connection drops out but I'll have to look deeper into it to determine if it's a simple fix. 

Not sure how common connectivity problems are for VPS but for context ec2 instance and hetzner server the code was preciously deployed on ran for months without any issue.
