### ISSUE TITLE
[FEATURE] Dump Detection

### ISSUE THREAD

**Issue by Juanjacinto123** [brianleect/binance-pump-alerts#8]
Price change detection could also be added, but in this case when prices go down. That is to say, exactly the same parameters but alerting when it is down. 

In this way the alert could indicate Dump or Pump. 

It would be a great feature, since both strong rises and strong falls in price, you can take advantage of them. 

And the use of this feature would be optional.

**Comment by brianleect** [comment]
Thanks for the feedback @Juanjacinto123 , the alert for dumps is definitely a great feature to have! Tweaking the code slightly has allowed me to add it in.

It can be accessed by enabling the parameter DUMP_ENABLED to be true.
